version: '3.3'

services:
  mysql:
    image: mysql:8.0.32
    networks:
      - blogdb
    environment:
      MYSQL_DATABASE: 'blog'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '127.0.0.1:$DB_PORT:3306'
    volumes:
      - $DB_DATA_PATH:/var/lib/mysql

networks:
  blogdb:
    external: true
