version: "3.3"

services:
  mysql:
    image: mysql:5.7.41
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - blogdb
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '$MYSQL_USER'
      # You can use whatever password you like
      MYSQL_PASSWORD: '$MYSQL_PASSWORD'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '$MYSQL_ROOT_PASSWORD'
      MYSQL_TCP_PORT: '$DB_PORT'
    ports:
      - '127.0.0.1:$DB_PORT:$DB_PORT'
    volumes:
      - $DB_DATA_PATH:/var/lib/mysql

networks:
  blogdb:
    external: true
