version: '3.3'

services:
  mysql:
    image: mysql:5.7.41
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - blogdb
    environment:
      # So you don't have to use root, but you can if you like
      - MYSQL_USER='user'
      # You can use whatever password you like
      - MYSQL_PASSWORD='password'
      # Password for root access
      - MYSQL_ROOT_PASSWORD='password'
      # computer timezone
      - TZ=${TIMEZONE}
    ports:
      - '127.0.0.1:${DB_PORT}:3306'
    volumes:
      - $DB_DATA_PATH:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - '4004:8080'

networks:
  blogdb:
    external: true
